travis:
  secure:
    BINSTAR_TOKEN: JX9xPuJfnmTaW8JVUaYFzPvM+6l4DY6WUyjhBqmkEV0nO6pq5HiPm5wzaeAmsyjNeeJgHFXMyX8cII8eRmf9axpDeTpaeRcHmIgEJGdH0Xfz3FezfNTSbTyqnDON/K0MOkOS3ePNqMH+9HVTWwefa+2uIv8F5JbxCT0jsewg3agMeVqxmO/XtaK3Ak2rz8nPexwKlOSP8nOwjBtKu2LVJrqTCJwf8nfgMPVtmEk2TvLCxE6l7U2AklLssWSBCMOmTLH6patVFhQZu4a+0U5Hf01yk3nh8XXenUdrUT73qHMpXCp18ZOgZkag0p37qfx5WwYgsk2qxO317Ow8tmm06EhrPkGQz8AXDdOju/abpKQaCzYaritxQxvVbKFWII4D9dzNs3govsX939CSkxoimbPLo7Ku+9A4V6vCNvyZrdrL4CU41H1EdlOSvBTjFR/zA0Nk4ufN4Tcf2D2gv3+hOXqWhn51u943NcxWhqGLwlk9b9G24dloGwt84hxZ+OBagsAqUY6UQ3hTjMDMTuE+OVZruiOuJ7ddcVo0Jl0+3Vhj9IHZnfrVFzyn/IrTPDzy9Sc5zTHolfokJXVDC8mXKZ2ZUphcFxcqLtuSO7SrMrDAR6BExf9uFuQtIywkhZc2r+FCjVRyOK9WmW85/HtOgIspZPHgYbSr4w4s4TsNoEs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
