travis:
  secure:
    BINSTAR_TOKEN: cbk9OKOxP8MNrWSQkH9ATyB8UibLzQ7N9VTJ/fSlTlzdNXvP+yHzDrol+PqGk77UW/55QJGK9MTCSmAae8RIjJhkeDu5Vv2cF6ybgzlzvE8sQGmobRJCZt4+BcLxMVVr7cedeCB+ycyc7BRfYIbgBCFT5VI0DpwifPlJpEoYEL4c7HgFIcmfsK5f8/ovAsK54Pu8cwgnn/avXYEt3w0P2evQh8FRvkDmMnW/Lfjy35jpD+uyL1s26Pt+WjkBGCKKH1BbdDpl5mNHwybDyK3aJf4M3jUtQCuA+VBKHUXhjAKPYcSeDbDISlDKAxtP0l7FWOHHtLmFZAlR4iA0hTD0mShU6SUBc2Z28eFmutpmDOGcQfKjI0yx86ZYoDHJfqDabR+ftyattYzZRJBdjVvIBo8zQKnDqG543OW5+8rer7rDKGo+VPP/N+3rrM1PLQG+/LVDPoOkxqh7lvdmR6oCJfgYInnbM5CEqzy8Gf5EvY3N796PpzJzQDubAVq8u293kNOGW0ozHj8UsxLzlrTzdu8w3bvKajXz73mHi4XFZXd1qkwXT7556JF8PxugTNKERt5Gh9ftmh5MUfnjYbAJJeaHmy2w6uThtYDWigBYzyuzYBRvkjL0lNA+OnC2g5cguu5o7Ol7QTH7qngNkEc9GeqaY7C0ED43ehCvq8LxQRY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
